package etat;



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
 import javax.swing.Timer;
/**
 *
 * @author Khady DIAGNE
 */
public class Feux extends javax.swing.JFrame {
    
              /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	 
			private final int nrouge = 10;
              private final int norange = 5;
              private final int nvert = 10;
              private FeuxContext traffic = new FeuxContext(); 
              
              static Timer time;
              static int r,o,v;
                
             

    /**
     * Creates new form feux
     */
    public Feux() {
        initComponents();
        
        rouge.setEnabled(true);
        orange.setEnabled(false);
        vert.setEnabled(false);
        
      start();
        
    }

    
        private void start(){
            
            int speed = 1000;
             r=nrouge;
             o=norange;
             v=nvert;
            ActionListener action = new ActionListener(){
            	
            	  @Override
                public void actionPerformed(ActionEvent ae) {
                    if(r>=0){
                        traffic.getStateRouge().Traitement();
                    }
                    else if(o>=0){
                        traffic.getStateOrange().Traitement();
                    }
                    else if(v>=0){
                        traffic.getStateVert().Traitement();
                        
                    }
                    else{
                        rouge.setEnabled(true);
                        orange.setEnabled(false);
                        vert.setEnabled(false);
                    
                        vert.setText(null);
                        r = nrouge;
                        o = norange;
                        v = nvert;
                    }
                   
                }
            };
            time = new Timer(speed, action);
            time.start();
            
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        rouge = new javax.swing.JLabel();
        orange = new javax.swing.JLabel();
        vert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rouge.setBackground(new java.awt.Color(255, 255, 255));
        rouge.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rouge.setForeground(new java.awt.Color(0, 0, 0));
        rouge.setIcon(new javax.swing.ImageIcon("images/rouge.PNG")); // NOI18N
        rouge.setOpaque(true);

        orange.setBackground(new java.awt.Color(255, 255, 255));
        orange.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        orange.setForeground(new java.awt.Color(0, 0, 0));
        orange.setIcon(new javax.swing.ImageIcon("images/jaune.PNG")); // NOI18N
        orange.setOpaque(true);

        vert.setBackground(new java.awt.Color(255, 255, 255));
        vert.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        vert.setForeground(new java.awt.Color(0, 0, 0));
        vert.setIcon(new javax.swing.ImageIcon("images/vert.PNG")); // NOI18N
        vert.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rouge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vert, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(rouge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vert)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feux().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    static  javax.swing.JLabel orange;
    static javax.swing.JLabel rouge;
    static javax.swing.JLabel vert;
    // End of variables declaration                   



	public Timer getTime() {
		return time;
	}


	public void setTime(Timer time) {
		this.time = time;
	}


	public int getR() {
		return r;
	}


	public void setR(int r) {
		this.r = r;
	}


	public int getO() {
		return o;
	}


	public void setO(int o) {
		this.o = o;
	}


	public int getV() {
		return v;
	}


	public void setV(int v) {
		this.v = v;
	}


	public static javax.swing.JLabel getOrange() {
		return orange;
	}


	public static void setOrange(javax.swing.JLabel orange) {
		Feux.orange = orange;
	}


	public static javax.swing.JLabel getRouge() {
		return rouge;
	}


	public static void setRouge(javax.swing.JLabel rouge) {
		Feux.rouge = rouge;
	}


	public static javax.swing.JLabel getVert() {
		return vert;
	}


	public static void setVert(javax.swing.JLabel vert) {
		Feux.vert = vert;
	}


	public int getNrouge() {
		return nrouge;
	}


	public int getNorange() {
		return norange;
	}


	public int getNvert() {
		return nvert;
	}
}
